baseURL = "https://sammckenzie.be"
defaultContentLanguageInSubdir = true
defaultContentLanguage = "en"
disableAliases = true
title = "Sam Mckenzie"

[outputs]
    section = ["HTML", "JSON"]

[languages.en]
    languageName = "English"
    weight = 1

    [[languages.en.params.nav_link]]
    link = "/#home"
    value = "Home"

    [[languages.en.params.nav_link]]
    link = "/#work"
    value = "Work"

    [[languages.en.params.nav_link]]
    link = "/#contact"
    value = "Contact"

    [[languages.en.params.nav_link]]
    link = "/blog"
    value = "Blog"

[languages.nl]
    languageName = "Nederlands"
    weight = 2

    [[languages.nl.params.nav_link]]
    link = "/#home"
    value = "Thuis"

    [[languages.nl.params.nav_link]]
    link = "/#work"
    value = "Projecten"

    [[languages.nl.params.nav_link]]
    link = "/#contact"
    value = "Contact"

    [[languages.nl.params.nav_link]]
    link = "/blog"
    value = "Blog"



[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4