baseURL = "https://sammckenzie.be"
languageCode = "en"
staticDir = "static"
title = "Sam Mckenzie"

[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]
    description = "My portfolio with a list of projects, achievements and current interests"
