baseURL = "https://sammckenzie.be"
languageCode = "en"
staticDir = "none"
title = "Sam Mckenzie"

[params]
    description = "My portfolio with a list of projects, achievements and current interests"
