[context.production.environment]
    HUGO_VERSION = "0.74.3"

# Hugo has been configured to generate static files for the en and nl languages in the folders en and nl
# Now, the index.html at the root of the site which would normally redirect the client to /en/ will proxy
# the request. This is much faster for the client and provides a better experience
# It also proxies to the correct lang site
# https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language

# EN language rewrites
# Rewrite from /index.html to /nl/index.html
[[redirects]]
    from = "/index.html"
    to = "/en/index.html"
    status = 200 # Force rewrite instead of redirect
    force = true # Override Hugo-generated index.html
    conditions = {Language = ["en"]} # Match Accept-Language headers that are configured for en
# Rewrite from / to /en/index.html
[[redirects]]
    from = "/"
    to = "/en/index.html"
    status = 200
    force = true
    conditions = {Language = ["en"]}

# NL language rewrites
# Rewrite from /index.html to /nl/index.html
[[redirects]]
    from = "/index.html"
    to = "/nl/index.html"
    status = 200
    force = true
    conditions = {Language = ["nl"]}
# Rewrite from / to /nl/index.html
[[redirects]]
    from = "/"
    to = "/nl/index.html"
    status = 200
    force = true
    conditions = {Language = ["nl"]}

# Other language rewrites
# Rewrite from /index.html to /en/index.html
[[redirects]]
    from = "/index.html"
    to = "/en/index.html"
    status = 200
    force = true
# Rewrite from / to /en/index.html
[[redirects]]
    from = "/"
    to = "/en/index.html"
    status = 200
    force = true